---

- name: "{{ name }}.check"
  shell: |
   timeout=$(crm_attribute -t crm_config -G -n stonith-timeout --quiet | sed -e 's/s$//')
   #
   # for aws and gcp we might need additional expected vars (name + fence_aws_...)
   #
   if [[cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1 ]]; then
     exit $([[ "${timeout}" -eq {{ expected[name + '.fence_azure_arm'] }} ]])
   else
     exit $([[ "${timeout}" -ge {{ expected[name + '.sbd'] }} ]])
   fi
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
