---

- name: "{{ name }}.check"
  lineinfile:
    path: /etc/corosync/corosync.conf
    regexp: '^\s*{{ key_name }}:\s*{{ expected[name] }}\s*$'
    state: absent
  register: result
  check_mode: true
  changed_when: false
  when: ansible_check_mode

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ result.found|default(false) | ternary(true, false) }}"
