---

- name: "{{ name }}.check"
  shell: |
    if [ -f /etc/sysconfig/sbd ]; then
      source /etc/sysconfig/sbd
    else
      exit 1
    fi

    IFS=';' sbdarray=( $SBD_DEVICE )

    for i in "${sbdarray[@]}"
      do
        device="${i//[[:space:]]/}"
        msgwait=$(/usr/sbin/sbd -d ${device} dump | grep -oP 'Timeout \(msgwait\)  *: \K\d+')|| echo ""
        watchdog=$(/usr/sbin/sbd -d ${device} dump | grep -oP 'Timeout \(watchdog\)  *: \K\d+')|| echo ""
        declare -i msgwait
        declare -i watchdog
        let watchdog*=2
        if [ $msgwait -lt $watchdog ]; then
          exit 1
        fi
      done
    exit 0

  register: config_updated
  check_mode: false
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"



