---

name: 1.5.2
group: Miscellaneous
labels: generic
description: |
  The `hacluster` user password has been changed from the default value `linux`
remediation: |
  ## Abstract
  The password of the `hacluster` user should be changed after setting up the cluster

  ## Remediation
  ```sudo passwd hacluster```

  ## References
  Azure:

    - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#install-the-cluster

  AWS:

    - https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-configuration.html

  GCP:

    - https://cloud.google.com/solutions/sap/docs/netweaver-ha-config-sles

  SUSE / KVM:

    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-initial-cluster-setup-using-ha-cluster-init

implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"
on_failure: warning

# check id. This value must not be changed over the life of this check
id: 790926
