---

name: 1.3.5
group: SBD
labels: generic
description: |
  SBD watchdog timeout is set to `{{ expected[name] }}`

  Not applicable to GCP, AWS
remediation: |
  ## Remediation
  Make sure you configure your SBD Watchdog Timeout to `{{ expected[name] }}` seconds as recommended on the best practices.

  The SBD is not used in GCP or AWS environments.

  ## References
  Azure:

    -  https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device

  AWS:

  GCP:

  SUSE / KVM:

    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-cluster-bootstrap-and-more

implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: B089BE
