---

- name: "{{ name }}.check"
  lineinfile:
    path: /etc/corosync/corosync.conf
    regexp: '^(\s*){{ key_name }}:(\s*)\S*(\s)*$'
    line: '\g<1>{{ key_name }}:\g<2>{{ expected[name] }}\g<3>'
    backrefs: yes
    #insertafter: 'totem {'
  register: config_updated
  when: ansible_check_mode

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
