---

name: 1.1.9
group: Corosync
labels: generic
description: |
  Corosync has at least 2 rings configured
remediation: |
  ## Abstract
  It is strongly recommended to add a second ring to the corosync communication.

  ## References
  Azure:
    - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
  AWS:
    - https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-configuration.html
  GCP:
    - https://cloud.google.com/solutions/sap/docs/sap-hana-ha-config-sles
  SUSE / KVM:
   - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-example-for-etccorosynccorosync-conf
   - section 9.1.3 in https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-adapting-the-corosync-and-sbd-configuration
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"
on_failure: warning

# check id. This value must not be changed over the life of this check
id: DA114A
