---

name: 1.3.4
group: SBD
labels: generic
description: |
  Multiple SBD devices are configured
remediation: |
  ## Abstract
  It is recommended to configure 3 SBD devices for production environments.

  ## References
  Azure:
    -  https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device
  AWS:
  GCP:
  SUSE / KVM:
    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#cha.hana-sr.scenario
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"
on_failure: warning

# check id. This value must not be changed over the life of this check
id: 61451E
