---

name: 1.1.2.runtime
group: Corosync
labels: generic
description: |
  Corosync is running with `consensus` timeout set to `{{ expected['1.1.2'] }}`
remediation: |
  ## Abstract
  The runtime value of the Corosync `consensus` timeout is not set as recommended.

  ## Remediation
  Adjust the corosync `consensus` timeout as recommended by the Azure best practices, and reload the corosync service.

  ## References
    Azure:
    - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
  AWS:
    - https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-configuration.html
  GCP:
    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-example-for-etccorosynccorosync-conf
  SUSE / KVM:
    - https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#id-example-for-etccorosynccorosync-conf
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: FB0E0D
