// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CallbacksClient is an autogenerated mock type for the CallbacksClient type
type CallbacksClient struct {
	mock.Mock
}

// Callback provides a mock function with given fields: executionID, event, payload
func (_m *CallbacksClient) Callback(executionID int64, event string, payload interface{}) error {
	ret := _m.Called(executionID, event, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string, interface{}) error); ok {
		r0 = rf(executionID, event, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
